name: OSPS Baseline Scan

on: [workflow_dispatch]

jobs:
  scan:
    runs-on: ubuntu-latest
    container:
      image: eddieknight/pvtr-github-repo:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      
      - name: Set PATH
        run: echo "PATH=$PATH:/.privateer/bin" >> $GITHUB_ENV

      - name: Add GitHub Secret to config file so it is protected in outputs
        run: |
          sed -i 's/{{ TOKEN }}/${{ env.TOKEN }}/g' ${{ github.workspace }}/.github/config.yml
        env:
          TOKEN: ${{ steps.app-token.outputs.token }}
      
      - name: Scan all repos
        run: privateer run --binaries-path /.privateer/bin --config ${{ github.workspace }}/.github/config.yml

      - name: Print Result
        run: for file in evaluation_results/**/*.log; do echo $file; cat $file; echo; done
